#!/bin/bash
# chkconfig: 2345 20 80
# description: hadoop namenode
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


if [ -f /etc/init.d/functions ] ; then
        . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
        . /etc/rc.d/init.d/functions
fi

prog=${0/*\/hbase-/}
case $prog in
    master )      DAEMON="Master"       ;;
    regionserver )        DAEMON="RegionServer"     ;;
    master-backup )      DAEMON="MasterBackup"       ;;
    zookeeper ) DAEMON="Zookeeper"  ;;
    * )
        echo "No such node type; stopping"
        exit 1
        ;;
esac

config (){

    [ -f /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh
    [ -f /etc/profile.d/hbase.sh] && . /etc/profile.d/hbase.sh

    if [ -z $HBASE_HOME ]; then
      export HBASE_HOME="/opt/hbase"
    fi
  
    echo "Using HBASE_HOME=$HBASE_HOME"

}

start () {
        echo -n $"Starting $prog: "
        config
        # start daemon
        su - hadoop -c "$HBASE_HOME/bin/hbase-daemon.sh start $prog"
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch /var/lock/subsys/$prog
        return $RETVAL
}

stop () {
        # stop daemon
        echo -n $"Stopping $prog: "
        config
        su - hadoop -c "$HBASE_HOME/bin/hbase-daemon.sh stop $prog"
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f /var/lock/subsys/$prog
}

restart() {
        stop
        sleep 5
        start
}

case $1 in
        start)
                start
        ;;
        stop)
                stop
        ;;
        restart)
                restart
        ;;
        condrestart)
                [ -f /var/lock/subsys/$prog ] && restart || :
        ;;
        reload)
        echo "No supported"
        ;;
        status)
        if pgrep -f "$DAEMON" &>/dev/null; then
            echo "$DAEMON running"
            exit 0
        else
            echo "$DAEMON stopped"
            exit 1
        fi
        ;;
        *)

        echo $"Usage: $prog {start|stop|restart|condrestart|reload|status}"
        exit 1
esac

exit $RETVAL

